// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqi8UD_VssgcS7m3TaAXlNvFeB6lk5ZAc',
    appId: '1:1037534072794:web:18de8432fab65b9f44bae3',
    messagingSenderId: '1037534072794',
    projectId: 'wakeup-74d89',
    authDomain: 'wakeup-74d89.firebaseapp.com',
    storageBucket: 'wakeup-74d89.appspot.com',
    measurementId: 'G-KH14TEPCSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOgDAs8oKPboGX1L7ZXn0JwaeB9RuecaU',
    appId: '1:1037534072794:android:c98a71c68122ce2a44bae3',
    messagingSenderId: '1037534072794',
    projectId: 'wakeup-74d89',
    storageBucket: 'wakeup-74d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbeBQgVWEnL0BzcEdRkrJ5P1Aaqag1DKQ',
    appId: '1:1037534072794:ios:cc3ebe72f5fe9e0444bae3',
    messagingSenderId: '1037534072794',
    projectId: 'wakeup-74d89',
    storageBucket: 'wakeup-74d89.appspot.com',
    iosBundleId: 'com.example.wakeupFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbeBQgVWEnL0BzcEdRkrJ5P1Aaqag1DKQ',
    appId: '1:1037534072794:ios:cc3ebe72f5fe9e0444bae3',
    messagingSenderId: '1037534072794',
    projectId: 'wakeup-74d89',
    storageBucket: 'wakeup-74d89.appspot.com',
    iosBundleId: 'com.example.wakeupFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqi8UD_VssgcS7m3TaAXlNvFeB6lk5ZAc',
    appId: '1:1037534072794:web:3d732bcb2492ca8a44bae3',
    messagingSenderId: '1037534072794',
    projectId: 'wakeup-74d89',
    authDomain: 'wakeup-74d89.firebaseapp.com',
    storageBucket: 'wakeup-74d89.appspot.com',
    measurementId: 'G-YLM1YT75GK',
  );

}